_pages/payment-accuracy/program-scorecards.html
Fixing links Payment accuracy program score cards
=> PaymentAccuracy fix

_layouts/priority-copy.html, _pages/FRPC.html, _pages/JFMIP.html, _pages/knowledge-sharing/knowledge-sharing-homepage.html, _pages/policies-guidance/policies-guidance-homepage.html, prioritypages/erm.md, prioritypages/fdt.md, prioritypages/financial-assistance.md, prioritypages/fmt.md, prioritypages/payment-integrity.md
adding meta description and key word
=> Migration fix

_config.yml
=> staging - unhide JFMIP menu link

_members/bloom-david.md
Removed Acting from D Bloom title
=> Ecasogp 2473 bloom title

_pages/payment-accuracy/payment-accuracy-resources.html, _pages/payment-accuracy/program-scorecards.html
=> Revert "Staging"

_policies_guidance/3-reasons-not-applying-for-cxo-fellows-program.md
=> Revert "6814 cxo blog"

.gitignore, Gemfile.lock, assets/js/career-planning.js, career-planning-tool/index.html
Please review changes and merge in development-wfm
=> Code changes to export CPT report as CSV

assets/css/career-planning.css, assets/js/facets.js, career-planning-tool/index.html
=> Revert "ECASOGP-8316: [DME][CFO] WFM ANDI Issue fixes"

_includes/meta.html
=> Revert "Hotfix: change styles link"

_data/coffa_ug_tabs.yml, _includes/carousel_homepage_top_coffa.html
View Changes here - 
https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/staging/coffa/
=> Fix Google Capitalization

_pages/payment-accuracy/payment-accuracy-numbers.html
Quick url fix:
preview: https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1269019/payment-accuracy/payment-accuracy-the-numbers/
=> url fixed for payment accuracy

_pages/payment-accuracy/payment-accuracy-numbers.html
**[Preview](https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/feature/RITM1276428/payment-accuracy/payment-accuracy-the-numbers/)**
**Description**
Replace the existing text under the “Annual Improper Payments Dashboard” heading on https://www.paymentaccuracy.gov/payment-accuracy-the-numbers/ with the following text: “The Payment Integrity Information Act of 2019 requires an annual publication to fulfill multiple statutory reporting requirements for both the agency and OMB. The interactive dashboard below lets you explore and compare payment integrity data through visualizations. The accompanying blog provides additional context to the government wide rate.”
The word "blog" should be hyperlinked with the following: …
=> updated content

_includes/resources-filters.html
Changes approved by PO
https://cm-jira.usa.gov/browse/OGPWEB-16793
Implemented archive button on CFO resources
Preview Link: https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/OGPWEB-16608/resources/
=> add resource button to cfo side

_data/coffa_ug_tabs.yml
Fixing the ANDI/AMP Issues in Uniform Guidance Page
https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/featture/OGPWEB-13002-clean/coffa/uniform-guidance-coffa/
=> updating tabs

_pages/coffa/members.html
=> unlink certain members

_config.yml, _pages/coffa/training-module.md, _pages/coffa/training.md, _pages/collections.md, prioritypages/_training-coffa.md
=> hide broken/unwanted links

_external_resources/Real-Property-Cost-Accounting-and-Sub-Object-Codes.md, _external_resources/accountability-funds-natural-disaster.md, _external_resources/applicant-eligibility-financial-Assistance-nonprofit-organizations.md, _external_resources/boilerplate-federal-financial-assistance.md, _external_resources/boilerplate-funding-opportunity.md, _external_resources/ca-23-01-implementation-congressional-budget-justification.md, _external_resources/ca-23-04-waiving-matching-fund-requirements-insular-areas.md, _external_resources/ca-24-03.md, _external_resources/ca-24-04.md, _external_resources/efficient-spending-federal-conferences.md, _external_resources/establishing-financial-administrative-controls-identify-access-fraud-risk.md, _external_resources/federal-real-property-data-elements.md, _external_resources/financial-reporting.md, _external_resources/government-charge-cards.md, _external_resources/implementing-save-award.md, _external_resources/improve-timeliness-grant-closeouts-federal-agencies.md, _external_resources/improving-collection-delinquent-debt.md, _external_resources/improving-quality-federal-spending.md, _external_resources/key-dates-fiscal-year-end-reporting-financial-report.md, _external_resources/personnel-data-collection.md, _external_resources/public-reporting-federal-conferences.md, _external_resources/reduce-footprint-policy.md, _external_resources/travel-conferences-05-28-2013.md, _external_resources/travel-conferences.md, _includes/resources-data.html, _sass/resources.scss
RITM1306624
Display archived on archived tiles
Add archived tag to requested resources
Changes approved by PO
[Preview Link](https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1307068/resources/)
=> Ritm1307068

_pages/payment-accuracy/program-scorecards.html
Changes approved by PO
RITM1313934
Updates payment accuracy content
Preview Link: https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1313934/payment-accuracy/payment-accuracy-high-priority-programs/
=> update paymentaccuracy program content

_pages/payment-accuracy/program-scorecards.html
Changes approved by PO
Update program scorecard q2 slot
RITM1344929
Preview Link: https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1344929/payment-accuracy/payment-accuracy-high-priority-programs/
=> update program scorecard q2 slot

assets/CPTT/courses.json
Add new courses
RITM1366845
[Preview Link](https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1366845/training-resources/)
=> update course filters

assets/CPTT/courses.json
Add new courses
RITM1366845
[Preview Link](https://cg-4ade7cd3-a036-4fb7-b1d5-bcef64cb3ddf.sites.pages.cloud.gov/preview/gsa/cfo.gov/RITM1366845/training-resources/)
=> Ritm1366845
